import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

const dist = "dist";
const assets = ["index.html", "elm.js", "app.js", "manifest.webmanifest",
  "icon.svg", "logo-fins.svg", "icon-192.png", "icon-512.png", "icon-maskable-512.png", "apple-touch-icon.png"]
  .filter((f) => { try { readFileSync(`${dist}/${f}`); return true; } catch { return false; } });

// Version = short hash of the built assets, so it changes only when content does.
const h = createHash("sha256");
for (const f of assets) h.update(readFileSync(`${dist}/${f}`));
const VERSION = (process.env.CF_PAGES_COMMIT_SHA || h.digest("hex")).slice(0, 12);

const sw = `// Generated by gen-sw.mjs — do not edit. Cache version busts on each build.
const VERSION = ${JSON.stringify(VERSION)};
const CACHE = "acr-" + VERSION;
const ASSETS = ${JSON.stringify(["./", ...assets])};

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)));
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

// Network-first for the app shell so a new deploy always wins when online, with a
// cache fallback for offline. (Cache-first was leaving stale builds on screen.)
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  e.respondWith((async () => {
    try {
      const res = await fetch(req);
      if (res && res.ok) {
        const c = await caches.open(CACHE);
        c.put(req, res.clone());
      }
      return res;
    } catch (_) {
      const cached = await caches.match(req);
      return cached || caches.match("./");
    }
  })());
});
`;
writeFileSync(`${dist}/sw.js`, sw);
console.log("sw.js written, version", VERSION, "assets", assets.length);
